### ISSUE TITLE
This error show when i press enter in console

### ISSUE THREAD

**Issue by burhanahmed92** [vinnyoodles/react-native-socket-io-example#17]
D:\react-native-socket-io\node_modules\mongodb\lib\mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (D:\react-native-socket-io\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at Pool.emit (events.js:159:13)
    at Connection.<anonymous> (D:\react-native-socket-io\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:254:19)
    at Connection.emit (events.js:159:13)
    at Socket.<anonymous> (D:\react-native-socket-io\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by harman-brar** [comment]
@burhanahmed92 @vinnyoodles were you able to resolve this error?

**Comment by vincent144** [comment]
You need to have a local mongodb instance running
